language: python
python:
 - "3.6"
 - "3.7"
cache: pip

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install coveralls
 - pip install nose

script:
 - nosetests -v --with-coverage --cover-package=api
 
 after_success:
- coveralls