language: python
#version
python:
  - "3.5"
  - "3.6"
  - "3.7"
 cache: pip 

 install:
  - pip install -r -requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose
 script:
  - nosetests --with-coverage app_tests.py 
 after_success:
  -coveralls 

